### ISSUE TITLE
De10 nano fpga support request. 

### ISSUE THREAD

**Issue by tylerw1369** [iotaledger/iota.go#103]
### Description
Is there any way to add the de10 nano fpga go code added to this?  It can be found on LampaLab's github here.  

https://github.com/LampaLab/giota/blob/master/pow_fpga.go

Thanks it would come in handy if it was able to be added.   =) 

## Motivation
There are some that are using the fpga as pow

### Requirements
Just add it to an available pow possibility 

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
No

**Comment by luca-moser** [comment]
@LampaLab's implementation should be adjusted to fulfill the `ProofOfWorkFunc` interface. If that is done, any user could import their library and use it in conjunction with the `API` object.
https://github.com/iotaledger/iota.go/blob/f036ff383d5a3760e16fd9c753b03e1baeeb1d55/pow/pow_go.go#L35

What I'd like to see is a separate repository from them which contains their FPGA `ProofOfWorkFunc`. I'd then link it in the README so user can download it separately if wanted.
