### ISSUE TITLE
Feature request: No track of all addresses

### ISSUE THREAD

**Issue by StarAurryon** [iotaledger/iota.go#113]
### Description
Badger store should keep a track of all addresses Hashes and there should be a method in account to retrieve them instead of using store.GetDepositAddresses(account.ID())

### Motivation
api.GetAccountData is deprecated.

### Am I planning to do it myself with a PR?
Yes

**Comment by StarAurryon** [comment]
Hello everyone,
I propose something like this to build a method from an account:
store.GetDepositAddresses(account.ID())
for key, value := range accAddr {
  addr, _ := address.GenerateAddress(seed, key, value.SecurityLevel, true)
}

However the checksum seem different from the one generated with account.AllocateDepositAddress(conds) that is using acc.setts.AddrGen(acc.lastKeyIndex, acc.setts.SecurityLevel, true).

Which is weird as the parameters seem to be quite the same.

Regards

**Comment by luca-moser** [comment]
Hey Star

>Badger store should keep a track of all addresses Hashes and there should be a method in account to retrieve them instead of using store.GetDepositAddresses(account.ID())

The account storage will ever only hold the addresses which are currently active for receiving deposits and not all addresses the account ever generated to save space.

>However the checksum seem different from the one generated with account.AllocateDepositAddress(conds) that is using acc.setts.AddrGen(acc.lastKeyIndex, acc.setts.SecurityLevel, true).

Is the checksum of the address different or the entire address? Note that `AllocateDepositAddress()`'s checksum is the checksum over all the values of the CDA and not just the address, that why it is different.

Can you please explain exactly your use case and what you're trying to achieve?

**Comment by StarAurryon** [comment]
Hello,

> Is the checksum of the address different or the entire address? Note that AllocateDepositAddress()'s checksum is the checksum over all the values of the CDA and not just the address, that why it is different.

Only the checksum part:  you have answered my question.

> Can you please explain exactly your use case and what you're trying to achieve?

I'm basically trying to send data from external temp sensors to the tangle (0 value transaction with MAM). I would like to get the results individually and per month (I would generate month * devices number addresses). 

My understanding is that I need first to retrieve the transactions and then decrypt the SignatureMessageFragment with MAM. And for that I need the destination address as we can't get the source one.

Thanks in advance,

BTW the discord link is not working anymore for me.

**Comment by luca-moser** [comment]
The account module is not MAM agnostic and has no concept on how to listen on addresses which were generated via MAM. Unfortunately this doesn't work. You'll have to write a separate program which simply uses the `api.API`.
