### ISSUE TITLE
Contributing question regarding PR without any API changes

### ISSUE THREAD

**Issue by siziyman** [iotaledger/iota.go#120]
Technically this is neither feature request nor bug, but I hope it's okay to post such questions here, since it's directly connected to code contribution process.

Should PR without API changes include additional tests and/or examples? I will provide motivation and explanation, of course.
I have read the guide in readme, it seems like the case in question isn't covered. 
I can provide test to prove that implementation change will be functionally equivalent to one already present in the repository, but it seems like such a test has no place in repository itself and probably should only exist as supplementary material for pull request (gist/link in description).

Thanks in advance!

**Comment by luca-moser** [comment]
Hey @siziyman 
If you don't change any method signatures or add actually any new methods, then you don't need to add additional tests as the one which are already present should cover it. However, if you found a bug in a given method which the current tests did not cover, we'd appreciate it if you could fix the test or add a new one for the specific input which yielded a bug.

**Comment by siziyman** [comment]
Yeah, sure, thanks for clarification!
