### ISSUE TITLE
Feature request: improve ValidTrytes implementation to work faster, get rid of regexp

### ISSUE THREAD

**Issue by siziyman** [iotaledger/iota.go#121]
### Description
Currently `trinary.ValidTrytes` func uses regular expression to validate string against a very simple pattern. Sadly, regular expressions in Golang standard library are quite slow (as will be proven further). It can be improved to work much faster, if the same check logic is implemented using for loop.

### Motivation
First of all, `ValidTrytes` is a relatively "hot" function - it's called in different places of SDK, and it'll be executed quite a lot. Client apps might be running it even more often, if there's more validation in business logic itself. And since IOTA is aimed to work closely with internet of things, and Golang is often used as a language to develop for smaller devices, it's quite useful to have that function implemented as efficient as possible, if it doesn't increase cognitive load and cost of support too much. In my opinion, it does not do that, so it's "safe" improvement.

### Requirements
- [ ] Rewrite `ValidTrytes` function getting rid of regular expression
- [ ] Provide benchmarks to verify performance improvement

### Am I planning to do it myself with a PR?
**Yes**.
PR is ready (code, example benchmarks), I'll finish writing it up and submit it right after the issue creation.

**Comment by luca-moser** [comment]
Merged https://github.com/iotaledger/iota.go/pull/122
