### ISSUE TITLE
Inconsistent input validation in trinary package

### ISSUE THREAD

**Issue by Wollac** [iotaledger/iota.go#136]
### Bug description

The way arguments are validated in the `trinary` package is not consistent at all:
- `TritsToTrytes` checks that the length is a multiple of 3, but not whether the `int8` actually represent valid trits. However, there is a test that suggests that the input values are also validated.
- `TrytesToTrits` checks that the input string indeed only contains valid tryte characters. There are tests for this behavior.
- `TritsToBytes` performs no checks on the trits, even an empty Trits slice is valid.
- `BytesToTrits` performs no checks that the bytes actually represent packed trits.
- `Pad` and `PadTrits` don't perform any checks.
- All other functions in `trinary` call one of those above and thus also have very inconsistent behavior.

### Suggested behavior

For consistency, I would suggest to remove any non-trivial (i.e. length) checks from all the conversion functions but offer dedicated check functions for trits, trytes and bytes in case the user needs to validate.

#### Reasoning:
- Most of the time these functions convert data that is the result of another library call and not user input, and as such known to be correct.
- These functions are performance critical and input validation often takes the same time as the actual conversion.
- For "random" input all of the conversion functions will panic even with out dedicated checks as the LUT are out-of-bounds.

### Am I planning to do it myself with a PR?
I can absolutely do an PR for this, if the suggested changes are acceptable.

**Comment by Wollac** [comment]
I've just realized that there is also the `guards` package that offers the same validation functionality (at least for trytes). 
What is the design idea for that package? Should this perhaps be consolidated?

**Comment by luca-moser** [comment]
I agree with you, that the conversion functions within the `trinary` package shouldn't do expensive checks on the input, but rather rely on the caller to actually check the validity via the guards package beforehand.

So this is what I'm going to do:
* Move any heavy validation logic into separate functions under the guard package (i.e., stuff which loops over the input) or other missing logic.
* Remove those from the `trinary` package and put reliance on the caller to do the checks beforehand manually

**Comment by luca-moser** [comment]
Actually, it seems that I can move the logic from within the error returning functions to Must().. and retain validation in the non Must()... functions. So the caller can choose whether panic to or get a slower function but returning an error.
