### ISSUE TITLE
Inconsistent signature of IntToTrits and IntToTrytes

### ISSUE THREAD

**Issue by Wollac** [iotaledger/iota.go#142]
### Bug description

The functions `IntToTrits` and `IntToTrytes` do not have the same signature:
- `IntToTrytes` has a mandatory parameter to specify the number of output trytes.
-  `IntToTrits` has no corresponding parameter. It internally uses `MinTrits` to determine the minimum number of trits to express the value and always outputs trits of that length. 

`MinTrits` is a rather costly operation as it involves several 64-bit multiplications. However, when looking at the usages of `IntToTrits` in iota.go, almost all of them combine it with `MustPadTrits` in order to get a fixed length and thus don't use the result of `MinTrits` in any way.

### Suggested behavior

`IntToTrits` and `IntToTrytes` should have the same signature as they essentially offer the same functionality and having the desired output length as a parameter is desirable for performance and convenience.
I would propose the following:
```go
func IntToTrits(value int64, numTrits int) Trits
```
If the user does not know the desired length, they can call `MinTrits` to find that value.

Maybe also consider:
1. making `numTrits` optional. This adds more convenience for the user, but also adds complexity that is technically not needed as `MinTrits` can be used for that.
2. returning `(Trits, bool)`, where the Boolean is used to signal an overflow when the value does not fit inside the provided number of trits. This offers a possibility for the user to check for overflows without using `MinTrits`, but I am not sure whether this very specific use case justifies the additional complexity.
3. providing `MinTrytes` in addition to `MinTrits`.

**Comment by luca-moser** [comment]
Fixed through #287
