### ISSUE TITLE
Implementation of extended APIs

### ISSUE THREAD

**Issue by HowJMay** [iotaledger/iota.go#148]
### Description
Extended APIs are implemented in `pyota` and `entangled`. Will them be implemented in `iota.go`. I think they do help in several scenarios.

### Motivation
Using extended APIs are convinient in several situations.

### Requirements
Just the same as the implementation in `pyota` and `entangled`

### Am I planning to do it myself with a PR?
neutral

**Comment by luca-moser** [comment]
Please clarify what extended API methods you mean. Thank you.

**Comment by HowJMay** [comment]
@luca-moser like the apis here
https://github.com/iotaledger/entangled/tree/develop/cclient/api/extended

**Comment by luca-moser** [comment]
This are already in.
