### ISSUE TITLE
Wrong assumption that security-level must be 1-3

### ISSUE THREAD

**Issue by frohal** [iotaledger/iota.go#179]
## Bug description

The constants for security-level goes from 1 to3

## Version

current master

There has never before been any problems using a security-level higher that 3 in the java-libs or the js-libs (thos might have changed now)
And still Hornet and COO verifies transactions from addresses on seclevel 5 
Bundle KWCSPUKCALYCDPRGDWEVSU9HRIJWUDCXJCDYPCZZJSBDY9SYR9H9X99QWUHPLDDY9UVSBWAKHAZFKSCCC is a sample of a recently performed transaction using an address created on seclevel5 thus using 5 input-tx'es to sign the transaction.
With current go-lib there would be no way of spending that 1 iota from that address.

**Comment by Wollac** [comment]
What exactly do you mean with "using a security-level higher than 3"? 

Are you talking about the generation of a private key with level 5? In that case, there is no security level 5. All the docs etc state that the max security level is 3. More importantly, it does not even increase the the security, if one would use a level > 3. In that case, the limiting factor is the bundle hash only consisting of three 27-tryte fragments, signing a fragment more than once doesn't change anything for collision or preimage attacks against the bundle hash. 

However, there is something that could be considered similar to validating signatures with level 5: These are multi-sig addresses. And there validation is supported in iota.go as you can see by Hornet verifying that particular bundle (and Hornet relying on iota.go for validation). However, for mult-sig the private key segments are not derived from only one seed, but from multiple independent seeds (e.g. 5 seeds each level one)! This is crucial for a secure N-out-N signature scheme, in which the participants don't need to trust each other. Thus, although it does not increase the overall security of the signature it still has its particular use-cases.
The multisig package in iota.go should provide support for these kinds of signatures, alternatively there are also solutions like  smidgen.

**Comment by frohal** [comment]
" In that case, there is no security level 5."
That's just semantics. a seclevel of 5 uses the two first sequences of the bundle has twice.  And the old libs has never imposed a limit on what the using code could give as sec'level other that it has to be greater than 0.  Using a seclevel of 5 just generates 5 key-parts from same 'subseed' and uses them all to hash it's way up to the address.
You may say that it's 'comparable' to mulitisig-addresses, but that would also be the case for an address with seclevel3 that are spread around on three clients. Multisig are different in the sense that they have several 'entrypoints' for generating the complete provate key. using selclevel 5 from one sunseed is different.

My point beeing that the current libs allow for secvalues greater than 3, and there might be addresses generated from such usage that holds funds, and by resticting new libs to a seclevel of 3 you effectivly locks up those funds.

**Comment by Wollac** [comment]
> That's just semantics.
I don't think this is true: Since there is no higher security than 3, generating private keys with more than 3 fragments has never been supported and it has always been the (ab)use of an API were the corresponding bound checks have been missing. Especially since such signatures can still be generated by custom implementations or perhaps even older versions (the resulting signature would be indistinguishable from multi-sig versions with the same number of fragments and of course validated in the node), this does not have to be a stopper to adding these bound checks in newer versions.

**Comment by frohal** [comment]
"I don't think this is true: Since there is no higher security than 3"
Well - it's true that the security of a signe transaction does not get 'better' if you use seclevel higher that 3, but there has not been restrictions in the libs against it, - so the 'support' for it has been there. 

I also discussed this with Paul H. when we discovered the bug in the java-lib that actually created a private key with 9 parts if you used a 243 trytes long seed at seclevel 3 - then this was fixed, but not then and not later has the lib been resticted to seclevel 1-3. 

but ofc - you decide wether you want to make this breaking change or not - It's not a problem now, since all older libs - using this is still wotking (just tested yesterday),but when Crysalis2.0-messages is a requirement for the network - also for WOTS-addresses, then this might be a problem sinde then the old clients won't work anymore, and if one needs to send from a seclevel5-address then he would need to buold his own cllient-lib, since the published lib no longer supports the secleve he's been using.

**Comment by frohal** [comment]
Ok - I stand corrected - the latest version of the java-lib actually did include such a restriction as well. So the this breaking change has actually been there for a while - I have not used the published libs for quite some time, since those never supoorted sending from two different seeds (two inputs from two different seeds) - when I used those, and not directly from a stored private-key (or one generated with another method than the m-buggy algorithm).
