### ISSUE TITLE
unable to generate address

### ISSUE THREAD

**Issue by olazpreton** [iotaledger/iota.go#207]
## Bug description

unable to generate address: each 243rd trit must be zero: invalid trit

## Version

api@master / go 1.14.3 linux/amd64

## Steps To reproduce the bug

generate an address

## Expected behaviour

should return an address

## Actual behaviour

exit status 1

## Errors

unable to generate address: each 243rd trit must be zero: invalid trit
exit status 1

**Comment by luca-moser** [comment]
Please provide code snippets.

**Comment by olazpreton** [comment]
```
package main

import (
	"fmt"
	"github.com/iotaledger/iota.go/address"
	"github.com/iotaledger/iota.go/trinary"
)

const seed = trinary.Trytes("WENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWENWEN")
const securityLevel = 2
const index = 0

func main() {
	addr, err := address.GenerateAddress(seed, index, securityLevel)
	must(err)
	fmt.Println("\nYour address is: ", addr)
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
```

**Comment by luca-moser** [comment]
The reason this code fails is that this seed is actually invalid.

**Comment by luca-moser** [comment]
This is actually the new code telling you that `N` is a malleable seed (because the last trit is discarded). You need to swap the last N for `W`.
