### ISSUE TITLE
Change in built NetworkPrefix for bech32 to allow for custom hrp

### ISSUE THREAD

**Issue by obany** [iotaledger/iota.go#237]
## Description

The current bech32 handling only allows mainnet and testnet prefixes, which won't work for private tangles.

## Motivation

If we want to use a custom bech32 hrp for a private tangle this is not currently possible as the bech32 methods are passed a NetworkPrefix int.

## Requirements

1. Change bech32 methods so that they are passed a hrp as a string
2. Change the inbuilt NetworkPrefixes to be strings, so they can be passed into the modified methods

**Comment by luca-moser** [comment]
Now the NetworkPrefix is simply a string and therefore any can be passed into the corresponding funcs.
