### ISSUE TITLE
Nice to have in the library

### ISSUE THREAD

**Issue by lunfardo314** [iotaledger/iota.go#301]
- taking foundry serialNumber from the `NativeTokenID` and `FoundryID` (this is very much wanted because serial number is a unique identifier of the foundry within alias). Something to use instead of `binary.LittleEndian.Uint32(id[20 : 20+4])`
- cloning `FoundryOutput`
- semantical validation of `TransactionEssence`, especially checking balancing of tokens (to be discussed)

**Comment by luca-moser** [comment]
Implemented in 3121ab3e3dfc5bb403b07b282f927c92637d8a49. `TransactionEssence`'s semantic validation is part of the `Transaction`'s validation. Make a separate issue specifying more precisely what you need.
