### ISSUE TITLE
Wrong json schema for foundry parsing

### ISSUE THREAD

**Issue by lzpap** [iotaledger/iota.go#309]
The json schema to parse a foundry output actually uses the schema of the nft output, hence foundry outputs can not be parsed correctly from json in https://github.com/iotaledger/iota.go/blob/3eddb537a34c6e4da322f05de224fe9d2017a254/output_foundry.go#L488-L499

**Comment by luca-moser** [comment]
fixed in 8ade0ad70608988eff1e4c61c6fd3c1df8b3a00a
