### ISSUE TITLE
`SerializedSize` wanted (GC optimized)

### ISSUE THREAD

**Issue by lunfardo314** [iotaledger/iota.go#310]
In Stardust VM we need to calculate resulting size of the tangle message on the fly several times per request in the block. 
Exceeding the size limit will cause a `protocol limit` exception in the VM. The VM will add serialized size of transaction to the tangle message overhead constant (received from outside). 

`iotago.SerializedSize()` . Input parameters:
- sizes of outputs (or sum of it)
- outputs, referenced in inputs 
- data payload size (always 0 in VM)
Result:
- size of the transaction= size(essence+unlock blocks)

`output.SerializedSize()` Outputs size calculation/GC optimization would be really nice: size calculation without real serialization (dummy buffer etc)

**Comment by luca-moser** [comment]
Added via [Feat: add Size() (](https://github.com/iotaledger/iota.go/pull/295/commits/b8145d4bc3824cbe405611bcbcf6ac2e2306fcd3)
