### ISSUE TITLE
Tag is optional in the tagged data payload

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/iota.go#316]
**Describe the bug**

According to [TIP-23](https://github.com/Wollac/protocol-rfcs/blob/tagged-data/tips/TIP-0023/tip-0023.md#syntactic-validation)
> When Tag Length is 0, the Tag has length 0 and is omitted.

When trying to send a tagged data payload with an empty Tag, for instance
```
'payload': {'type': 5, 'tag': '', 'data': '48656c6c6f20576f726c64'}
```

the library throws out an error
```
unable to serialize tagged data tag: tag is below min size: code=400, message=invalid parameter
```

**Comment by luca-moser** [comment]
Fixed in 449cb4551881070806eb522d345a32ad7909706f
