### ISSUE TITLE
Update milestones core api routes

### ISSUE THREAD

**Issue by lzpap** [iotaledger/iota.go#345]
According to[ TIP-25](https://github.com/iotaledger/tips/blob/6a926b3028986571eab2b19952c033784b7fd512/tips/TIP-0025/core-rest-api.yaml), the milestone related api routes changed to:
 - `/api/v2/milestones/index/{index}`: returns milestones by index
 - `/api/v2/milestones/milestoneId/{milestoneId}`: return milestones by ID
 - (didn't change) `/api/v2/milestones/{index}/utxo-changes`: return utxo changes for a milestone

**Comment by luca-moser** [comment]
Updated in [47dbc0b](https://github.com/iotaledger/iota.go/pull/295/commits/47dbc0bf300804e6e0aad5a38d00b671dff8c5db)
