### ISSUE TITLE
V3 protocol params for reward still wrong

### ISSUE THREAD

**Issue by shufps** [iotaledger/iota.go#646]
This line was changed but unfortunately was overwritten again in some later merge:

https://github.com/iotaledger/iota.go/blob/develop/api_v3_protocol_parameters.go#L239

Probably It should be:
https://github.com/iotaledger/iota.go/pull/635/files#diff-0cb2f17ed0f43baefd0c5d161ad746d7caf97706365aeb955bcb29f4426ec4dbR50

**Comment by PhilippGackstatter** [comment]
Fixed by #641.
