### ISSUE TITLE
Fix `MaxBlockWork` calculation

### ISSUE THREAD

**Issue by muXxer** [iotaledger/iota.go#676]
I saw that the `MaxBlockWork` didn't take into account that inputs could be unlocked by MultiUnlocks with 10 Ed25519 signatures each.

But the current "fix" is also not totally correct, because that many signatures would not even fit in a block.

Should we instead create different "scenarios" to calculate the max possible amount of "something" that would fit in a block, and then take the max value? Because that might change depending on the current WorkScore values.

**Comment by cyberphysic4l** [comment]
I actually think your fix is sufficient and better than trying to work out the variants we can have. The most important function of the MaxBlockWork() function is to give an upper bound on the WorkScore of a block and the fix you did is not a tight upper bound but it serves the purpose.

**Comment by cyberphysic4l** [comment]
Updated the comment to remove TODO and explain reason it is ok to have an overestimation of maximum block workscore.
